"""
Semantic Matcher Engine for SETU.

PRD Section 18.1 & User Requirement:
- SBERT / Sentence Transformers (all-MiniLM-L6-v2) on CPU.
- Hybrid matching: Semantic similarity + Capability relevance + Sector relevance.
- Fast cached inference: precomputed startup embeddings, 1 query embedding at runtime.
- No paid AI API. No GPU required.
"""

import os
import sys
import logging
import numpy as np
from typing import List, Dict, Any, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    from database.config import (
        MATCHING_SEMANTIC_WEIGHT,
        MATCHING_CAPABILITY_WEIGHT,
        MATCHING_SECTOR_WEIGHT,
        SBERT_MODEL_NAME,
    )
except ImportError:
    from config import (
        MATCHING_SEMANTIC_WEIGHT,
        MATCHING_CAPABILITY_WEIGHT,
        MATCHING_SECTOR_WEIGHT,
        SBERT_MODEL_NAME,
    )
from preprocessing import (
    build_challenge_search_text,
    build_startup_search_text,
    tokenize,
    GENERIC_TECH_TERMS,
)

logger = logging.getLogger(__name__)

# In-memory embedding cache: {startup_id: numpy_array}
_STARTUP_EMBEDDING_CACHE: Dict[int, np.ndarray] = {}
_SBERT_MODEL = None
_CACHE_FILE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "embeddings_cache.npz")


def get_model():
    """Lazily loads SentenceTransformer model on CPU."""
    global _SBERT_MODEL
    if _SBERT_MODEL is None:
        try:
            from sentence_transformers import SentenceTransformer
            logger.info(f"Loading SentenceTransformer model '{SBERT_MODEL_NAME}' on CPU...")
            # Enforce CPU execution
            _SBERT_MODEL = SentenceTransformer(SBERT_MODEL_NAME, device="cpu")
            logger.info("SentenceTransformer loaded successfully.")
        except Exception as e:
            logger.warning(f"Could not load SentenceTransformer '{SBERT_MODEL_NAME}': {e}. Using TF-IDF fallback.")
            _SBERT_MODEL = "TF_IDF_FALLBACK"
    return _SBERT_MODEL


def cosine_similarity(v1: np.ndarray, v2: np.ndarray) -> float:
    """Calculates cosine similarity between two 1D or 2D vectors."""
    dot = np.dot(v1, v2)
    norm1 = np.linalg.norm(v1)
    norm2 = np.linalg.norm(v2)
    if norm1 == 0 or norm2 == 0:
        return 0.0
    return float(dot / (norm1 * norm2))


def compute_embedding(text: str) -> np.ndarray:
    """Encodes a single string into a normalized embedding vector."""
    model = get_model()
    if model != "TF_IDF_FALLBACK" and hasattr(model, "encode"):
        emb = model.encode(text, convert_to_numpy=True, normalize_embeddings=True)
        return emb.astype(np.float32)

    # Fallback pseudo-embedding via TF-IDF hashing if model unavailable
    from sklearn.feature_extraction.text import HashingVectorizer
    vec = HashingVectorizer(n_features=384, alternate_sign=False)
    emb = vec.transform([text]).toarray()[0]
    norm = np.linalg.norm(emb)
    return (emb / norm if norm > 0 else emb).astype(np.float32)


def compute_and_cache_startup_embeddings(startups: List[Dict[str, Any]]):
    """
    Precomputes and caches embeddings for a list of startups.
    Called on startup creation, update, or data import (PRD Section 18.1).
    """
    global _STARTUP_EMBEDDING_CACHE
    model = get_model()

    texts = [build_startup_search_text(s) for s in startups]
    ids = [s["id"] for s in startups]

    if not texts:
        return

    if model != "TF_IDF_FALLBACK" and hasattr(model, "encode"):
        embeddings = model.encode(texts, batch_size=16, convert_to_numpy=True, normalize_embeddings=True)
    else:
        from sklearn.feature_extraction.text import HashingVectorizer
        vec = HashingVectorizer(n_features=384, alternate_sign=False)
        mat = vec.transform(texts).toarray()
        norms = np.linalg.norm(mat, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        embeddings = mat / norms

    for s_id, emb in zip(ids, embeddings):
        _STARTUP_EMBEDDING_CACHE[s_id] = emb.astype(np.float32)

    # Persist cache to disk
    try:
        id_arr = np.array(ids, dtype=np.int32)
        emb_arr = np.array(embeddings, dtype=np.float32)
        engine = "sbert" if model != "TF_IDF_FALLBACK" and hasattr(model, "encode") else "tfidf_fallback"
        np.savez_compressed(
            _CACHE_FILE_PATH,
            ids=id_arr,
            embeddings=emb_arr,
            model_name=np.array(SBERT_MODEL_NAME),
            engine=np.array(engine),
        )
    except Exception as e:
        logger.warning(f"Could not persist embeddings cache to disk: {e}")


def load_cached_embeddings_from_disk():
    """Load cached embeddings only when they were generated by the same engine.

    This prevents a TF-IDF fallback cache created on a machine without
    Sentence Transformers from silently surviving after SBERT is installed.
    """
    global _STARTUP_EMBEDDING_CACHE
    if not os.path.exists(_CACHE_FILE_PATH):
        return
    try:
        data = np.load(_CACHE_FILE_PATH, allow_pickle=False)
        cached_model = str(data["model_name"]) if "model_name" in data else ""
        cached_engine = str(data["engine"]) if "engine" in data else "tfidf_fallback"
        current_model = get_model()
        current_engine = "sbert" if current_model != "TF_IDF_FALLBACK" and hasattr(current_model, "encode") else "tfidf_fallback"

        if cached_model != SBERT_MODEL_NAME or cached_engine != current_engine:
            logger.info(
                "Ignoring stale embedding cache (cached=%s/%s, current=%s/%s). Rebuilding.",
                cached_engine, cached_model, current_engine, SBERT_MODEL_NAME,
            )
            return

        ids = data["ids"]
        embs = data["embeddings"]
        for s_id, emb in zip(ids, embs):
            _STARTUP_EMBEDDING_CACHE[int(s_id)] = emb.astype(np.float32)
        logger.info("Loaded %s cached startup embeddings from disk.", len(_STARTUP_EMBEDDING_CACHE))
    except Exception as e:
        logger.warning(f"Error reading embeddings cache file: {e}")


def calculate_sector_similarity(challenge_sector: str, startup_sector: str) -> float:
    """
    Computes sector relevance (0.0 to 1.0).
    Aligns with PRD hybrid matching rules.
    """
    if not challenge_sector or not startup_sector:
        return 0.5  # Neutral when unspecified

    c_sec = challenge_sector.lower().strip()
    s_sec = startup_sector.lower().strip()

    if c_sec == s_sec or c_sec in s_sec or s_sec in c_sec:
        return 1.0

    # Sector correlation groups
    groups = [
        {"energy", "power", "utility", "utilities", "electricity", "grid"},
        {"water", "sanitation", "sewage", "pipeline", "groundwater"},
        {"waste", "municipal", "recycling", "sanitation", "cleanliness"},
        {"health", "medical", "telemedicine", "hospital", "healthcare"},
        {"transport", "traffic", "mobility", "roads", "highways", "urban"},
        {"education", "schools", "skilling", "learning", "literacy"},
        {"agriculture", "farming", "crop", "rural", "farmer"},
    ]

    c_tokens = set(tokenize(c_sec))
    s_tokens = set(tokenize(s_sec))

    for group in groups:
        if (c_tokens & group) and (s_tokens & group):
            return 0.85

    return 0.10


def calculate_capability_relevance(challenge: Dict[str, Any], startup: Dict[str, Any]) -> float:
    """
    Evaluates overlap between required challenge capabilities and startup capabilities.
    Explicitly removes generic tech buzzwords so real domain capabilities decide the score.
    """
    c_caps = (challenge.get("capabilities_needed") or challenge.get("skills_needed") or "").lower()
    s_caps = (startup.get("capabilities") or startup.get("tags") or "").lower()

    if not c_caps or not s_caps:
        return 0.5

    c_tokens = set(tokenize(c_caps)) - GENERIC_TECH_TERMS
    s_tokens = set(tokenize(s_caps)) - GENERIC_TECH_TERMS

    if not c_tokens or not s_tokens:
        return 0.3

    overlap = c_tokens & s_tokens
    # Jaccard + domain recall
    recall = len(overlap) / len(c_tokens)
    jaccard = len(overlap) / len(c_tokens | s_tokens)
    return float(min(1.0, (recall * 0.7 + jaccard * 0.3) * 1.5))


def match_startups_semantic(
    challenge: Dict[str, Any],
    startups: List[Dict[str, Any]],
    top_n: int = 50,
) -> List[Dict[str, Any]]:
    """
    Executes hybrid semantic matching:
      Final Fit Score = 100 * (0.70 * Semantic_Sim + 0.20 * Capability_Rel + 0.10 * Sector_Rel)

    Returns ranked list of candidate startups.
    """
    if not startups:
        return []

    # Ensure disk cache is loaded if memory cache is empty
    if not _STARTUP_EMBEDDING_CACHE and os.path.exists(_CACHE_FILE_PATH):
        load_cached_embeddings_from_disk()

    # 1. Build rich challenge text and compute single query embedding
    challenge_text = build_challenge_search_text(challenge)
    query_embedding = compute_embedding(challenge_text)

    # 2. Check for missing startup embeddings in cache and compute them
    missing = [s for s in startups if s["id"] not in _STARTUP_EMBEDDING_CACHE]
    if missing:
        compute_and_cache_startup_embeddings(missing)

    c_sector = challenge.get("sector") or challenge.get("department") or ""

    results = []
    for s in startups:
        s_id = s["id"]
        s_emb = _STARTUP_EMBEDDING_CACHE.get(s_id)
        if s_emb is None:
            s_emb = compute_embedding(build_startup_search_text(s))
            _STARTUP_EMBEDDING_CACHE[s_id] = s_emb

        # Semantic cosine similarity (raw -1 to 1 scaled to 0 to 1)
        raw_sim = cosine_similarity(query_embedding, s_emb)
        # Normalize: SBERT cosine similarities for topical domains typically range from 0.1 to 0.8
        semantic_sim = float(np.clip((raw_sim + 0.1) / 0.9, 0.0, 1.0))

        # Capability relevance
        cap_sim = calculate_capability_relevance(challenge, s)

        # Sector relevance
        sec_sim = calculate_sector_similarity(c_sector, s.get("sector") or s.get("industry") or "")

        # Combined hybrid score (Rules are data - weights from config)
        hybrid_score = (
            MATCHING_SEMANTIC_WEIGHT * semantic_sim
            + MATCHING_CAPABILITY_WEIGHT * cap_sim
            + MATCHING_SECTOR_WEIGHT * sec_sim
        )
        match_score = round(float(np.clip(hybrid_score * 100.0, 0.0, 100.0)), 1)

        results.append({
            "startup_id": s_id,
            "startup": s,
            "match_score": match_score,
            "semantic_similarity": round(semantic_sim * 100.0, 1),
            "capability_relevance": round(cap_sim * 100.0, 1),
            "sector_relevance": round(sec_sim * 100.0, 1),
        })

    # Sort descending by match_score
    results.sort(key=lambda r: r["match_score"], reverse=True)
    return results[:top_n]
